// <auto-generated />
using System;
using Benefits.Administration.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Benefits.Administration.Infrastructure.Migrations
{
    [DbContext(typeof(BenefitsDbContext))]
    [Migration("20231103153951_2023_Benefits")]
    partial class _2023_Benefits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Benefit", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DependentCost")
                        .HasColumnType("float");

                    b.Property<double>("EmployeeCost")
                        .HasColumnType("float");

                    b.Property<int>("PayPeriods")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.HasKey("ID");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            DependentCost = 500.0,
                            EmployeeCost = 1000.0,
                            PayPeriods = 26,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Dependent", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EmployeeID")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Dependents");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            EmployeeID = 1L,
                            FirstName = "Padme",
                            LastName = "Skywalker",
                            Type = 1
                        },
                        new
                        {
                            ID = 2L,
                            EmployeeID = 1L,
                            FirstName = "Luke",
                            LastName = "Skywalker",
                            Type = 2
                        },
                        new
                        {
                            ID = 3L,
                            EmployeeID = 1L,
                            FirstName = "Leah",
                            LastName = "Skywalker",
                            Type = 2
                        },
                        new
                        {
                            ID = 4L,
                            EmployeeID = 2L,
                            FirstName = "John",
                            LastName = "Connor",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Discount", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<long>("BenefitID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BenefitID");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Amount = 0.10000000000000001,
                            BenefitID = 1L,
                            IsActive = true,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Employee", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<double>("Income")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            FirstName = "Anakin",
                            Income = 52000.0,
                            LastName = "Skywalker"
                        },
                        new
                        {
                            ID = 2L,
                            FirstName = "Sarah",
                            Income = 52000.0,
                            LastName = "Connor",
                            MiddleName = "J"
                        },
                        new
                        {
                            ID = 3L,
                            FirstName = "Bruce",
                            Income = 52000.0,
                            LastName = "Wayne",
                            MiddleName = "Thomas"
                        });
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Dependent", b =>
                {
                    b.HasOne("Benefits.Administration.Application.Entities.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Discount", b =>
                {
                    b.HasOne("Benefits.Administration.Application.Entities.Benefit", "Benefit")
                        .WithMany("Discounts")
                        .HasForeignKey("BenefitID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
