// <auto-generated />
using Benefits.Administration.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Benefits.Administration.Infrastructure.Migrations
{
    [DbContext(typeof(BenefitsDbContext))]
    [Migration("20240623215718_2024_BenefitDiscount")]
    partial class _2024_BenefitDiscount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Benefit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("DependentCost")
                        .HasColumnType("float");

                    b.Property<double>("EmployeeCost")
                        .HasColumnType("float");

                    b.Property<int>("PayPeriods")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DependentCost = 500.0,
                            EmployeeCost = 1000.0,
                            PayPeriods = 26,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.BenefitDiscount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BenefitId")
                        .HasColumnType("bigint");

                    b.Property<long>("DiscountId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("DiscountId");

                    b.ToTable("BenefitDiscount");
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Dependent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Dependents");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EmployeeId = 1L,
                            FirstName = "Padme",
                            LastName = "Skywalker",
                            Type = 1
                        },
                        new
                        {
                            Id = 2L,
                            EmployeeId = 1L,
                            FirstName = "Luke",
                            LastName = "Skywalker",
                            Type = 2
                        },
                        new
                        {
                            Id = 3L,
                            EmployeeId = 1L,
                            FirstName = "Leah",
                            LastName = "Skywalker",
                            Type = 2
                        },
                        new
                        {
                            Id = 4L,
                            EmployeeId = 2L,
                            FirstName = "John",
                            LastName = "Connor",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Discount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 0.10000000000000001,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Income")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Anakin",
                            Income = 52000.0,
                            LastName = "Skywalker"
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Sarah",
                            Income = 52000.0,
                            LastName = "Connor",
                            MiddleName = "J"
                        },
                        new
                        {
                            Id = 3L,
                            FirstName = "Bruce",
                            Income = 52000.0,
                            LastName = "Wayne",
                            MiddleName = "Thomas"
                        });
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.BenefitDiscount", b =>
                {
                    b.HasOne("Benefits.Administration.Application.Entities.Benefit", null)
                        .WithMany("BenefitDiscounts")
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Benefits.Administration.Application.Entities.Discount", null)
                        .WithMany("BenefitDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Dependent", b =>
                {
                    b.HasOne("Benefits.Administration.Application.Entities.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Benefit", b =>
                {
                    b.Navigation("BenefitDiscounts");
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Discount", b =>
                {
                    b.Navigation("BenefitDiscounts");
                });

            modelBuilder.Entity("Benefits.Administration.Application.Entities.Employee", b =>
                {
                    b.Navigation("Dependents");
                });
#pragma warning restore 612, 618
        }
    }
}
